pizza: $(var pizza_type)
anonymous_name: $(anon leo)
favorite_brother: $(env BROTHER_NAME mikey)
filename: $(filename)
directory: $(dirname)
list_exec: $(find-exec ls)
list_output: $(command ls)
version: ROS $(env ROS_VERSION)
circumference: $(eval 2.*3.1415*$(var radius))
