does_machines:
  ros__parameters:
    pizza: $(var pizza_type)
    anonymous_name: $(anon leo)
    favorite_brother: $(env BROTHER_NAME mikey)
    filename: $(filename)
    directory: $(dirname)
    release_exec: $(find-exec lsb_release)
    release_output: $(command 'lsb_release -ds')
    version: ROS $(env ROS_VERSION)
    circumference: $(eval 2.*3.1415*$(var radius))
